import os

from dataclasses import dataclass
from tqdm import tqdm
from pathlib import Path

from matplotlib import pyplot as plt

import scipy
import torch
from torch.utils.data import DataLoader, TensorDataset

import hydra
from hydra.core.config_store import ConfigStore
from omegaconf import MISSING, OmegaConf

from mimo.models import get_model
from mimo.losses import add_noise_to_data, score_training_loss
from mimo.data import get_data, complex_to_real, real_to_complex
from mimo.train import TrainConfig


@dataclass
class SamplingConfig:
    model_path: Path = MISSING
    data_path: Path = MISSING
    save_dir: Path = MISSING

    batch_size: int = 4
    device: str = "cuda"

    alpha_0: float | str = "auto"
    beta: float = 1

    num_steps_inner: int = 1

    def __post_init__(self):
        if not self.model_path.is_file():
            raise ValueError("Model file must exist and be generated by mimo.train!")

        if not self.data_path.is_file():
            raise ValueError("Data file must exist and be generated by mimo.cdl!")


cs = ConfigStore.instance()
cs.store(name="sampling", node=SamplingConfig)


def compute_epsilon(
    num_steps_inner: int, noise_step_factor: float, min_noise_level: float
) -> float:
    # Cost function
    def cost(epsilon: float) -> float:
        ratio = epsilon / min_noise_level**2
        denominator = min_noise_level**2 - min_noise_level**2 * (1 - ratio) ** 2
        fraction = 2 * epsilon / denominator

        value = (1 - ratio) ** (2 * num_steps_inner) * (
            (1 / noise_step_factor) ** 2 - fraction
        ) + fraction
        return abs(1 - value)

    # Line search
    result = scipy.optimize.brute(cost, ((1e-13, 1e-7),), Ns=100000, full_output=True)
    return result[0]


def sample_from_model(
    model: torch.nn.Module,
    num_steps_outer: int,
    num_steps_inner: int,
    alpha_0: float,
    r: float,
    beta: float,
    noise_levels: torch.Tensor,
    batch_size: int,
    sample_size: tuple[int],
    measurements: torch.Tensor | None = None,
    pilots: torch.Tensor | None = None,
    measurement_noise_std: float | None = None,
) -> torch.Tensor:
    # Initialize process directly with real-valued signals
    current = noise_levels[0] * torch.randn(
        (batch_size, 2, *sample_size),
        dtype=torch.float32,
        device=noise_levels.device,
    )

    # Check if there's a mismatch between number of outer steps and noise levels
    if num_steps_outer != len(noise_levels):
        raise RuntimeError("Unequally spaced sampling not yet supported!")

    for outer_step in tqdm(range(num_steps_outer)):
        step_size = torch.tensor(
            alpha_0 * r ** (2 * outer_step), dtype=torch.float32, device=noise_levels.device
        )
        noise_std = torch.sqrt(2 * torch.tensor(beta, device=noise_levels.device) * step_size)
        for _ in range(num_steps_inner):
            # Predict with diffusion model
            labels = outer_step * torch.ones(
                len(current), device=current.device, dtype=torch.long
            )
            output = model(current, labels)
            noise = torch.randn_like(output)

            # Apply unconditional update equation
            current = current + step_size * output + noise_std * noise

            # Apply conditional update equation
            if measurements is not None:
                if pilots is None or measurement_noise_std is None:
                    raise RuntimeError(
                        "Pilots and measurement noise must be passed together with measurements!"
                    )
                reconstructed_measurements = torch.matmul(real_to_complex(current), pilots)
                conditional = torch.matmul(
                    reconstructed_measurements - measurements,
                    pilots.transpose(-1, -2).conj(),
                ) / (measurement_noise_std**2 + noise_std**2)

                current = current - step_size * complex_to_real(conditional)

            with open("sampling_log_repro.txt", "a") as f:
                f.write(
                    f"Step {outer_step}: Alpha {step_size.item():.6f}, Noise (real) {noise_std.item():.6f}\n"
                )

        # Early exit if we encounter NaN
        if current.isnan().any():
            print("WARNING: Sampling exited early because of NaN values!")
            return current

    return current


def plot_paired_data(top_row: torch.Tensor, bottom_row: torch.Tensor, save_file: Path):
    if top_row.shape != bottom_row.shape:
        raise ValueError("Cannot plot differently shaped top/bottom row samples!")
    b, h, w = top_row.shape

    plot_ratio = (b * w) / (2 * h)
    plt.figure(figsize=(4 * plot_ratio, 4))
    for i in range(b):
        plt.subplot(2, b, i + 1)
        plt.imshow(top_row[i].abs().cpu().numpy())
        plt.axis("off")
        plt.subplot(2, b, i + 1 + b)
        plt.imshow(bottom_row[i].abs().cpu().numpy())
        plt.axis("off")
    plt.tight_layout()
    plt.savefig(
        save_file,
        dpi=300,
        bbox_inches="tight",
    )
    plt.close()


@hydra.main(version_base=None, config_name="sampling")
def main(cfg: SamplingConfig) -> None:
    cfg = OmegaConf.to_object(cfg)
    os.makedirs(cfg.save_dir, exist_ok=True)
    # Load model and configuration
    contents = torch.load(cfg.model_path, map_location="cpu")
    cfg_train: TrainConfig = contents["cfg"]

    # Get validation data
    val_data, val_config = get_data(cfg.data_path)
    val_dataset = TensorDataset(val_data)
    val_dataloader = DataLoader(val_dataset, batch_size=cfg.batch_size, shuffle=True)
    val_samples = next(iter(val_dataloader))[0].to(cfg.device)

    # Instantiate model
    model = get_model(
        cfg_train.arch,
        cfg_train.max_noise_level,
        cfg_train.num_noise_levels,
        cfg_train.noise_step_factor,
        num_rx=val_config.num_rx,
        num_tx=val_config.num_tx,
    ).to(cfg.device)
    # Load model weights
    model.load_state_dict(contents["model_state_dict"], strict=True)
    model.eval()

    # Compute recommended epsilon
    if cfg.alpha_0 == "auto":
        epsilon = compute_epsilon(
            1,
            1 / cfg_train.noise_step_factor,
            cfg_train.max_noise_level
            * cfg_train.noise_step_factor ** (cfg_train.num_noise_levels - 1),
        )
        alpha_0 = epsilon * (1 / cfg_train.noise_step_factor) ** (
            2 * (cfg_train.num_noise_levels - 1)
        )
    else:
        alpha_0 = cfg.alpha_0

    # Compute validation loss
    stddev_idx = torch.randint(0, len(model.sigmas), (len(val_samples),), device=cfg.device)
    stddev = model.sigmas[stddev_idx]
    val_samples = complex_to_real(val_samples)
    val_samples_noisy, noise = add_noise_to_data(val_samples, stddev)

    # Pass through model
    output = model(val_samples_noisy, stddev_idx)
    val_loss = score_training_loss(output, noise, stddev)
    print(f"Val. Loss {val_loss.item():.2f}")

    # Generate synthetic data
    with torch.inference_mode():
        synthetic_samples = sample_from_model(
            model,
            len(model.sigmas),
            cfg.num_steps_inner,
            alpha_0,
            cfg_train.noise_step_factor,
            cfg.beta,
            model.sigmas,
            cfg.batch_size,
            sample_size=(val_samples.shape[-2], val_samples.shape[-1]),
        )

    # Plot the synthetic data
    plot_paired_data(
        real_to_complex(val_samples).conj().transpose(-1, -2).contiguous(),
        real_to_complex(synthetic_samples).conj().transpose(-1, -2).contiguous(),
        cfg.save_dir / "unconditional.png",
    )


if __name__ == "__main__":
    main()
